name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: gradle
        run: gradle init
      - name: Build the app
        run: gradle build --dry-run
      - name: flutter
        run: flutter install
      - name: release
        run: flutter run

